import type { Vehicle, VehicleSource } from "@/lib/types";
import { vehicleSlug } from "@/lib/utils";
import { mulberry32, pick, randInt, chance, type Rng } from "@/lib/server/random";

// Dados de demonstração — nenhum veículo, placa ou foto real. Usados apenas
// para o ambiente de desenvolvimento enquanto não há integração com o
// estoque real (ver lib/server/db.ts).

type SeedVehicle = Omit<Vehicle, "id" | "slug" | "photos" | "createdAt" | "updatedAt" | "source"> & {
  source?: VehicleSource;
  photoAngles?: string[];
};

const daysAgo = (n: number) => new Date(Date.now() - n * 86400000).toISOString();

const base: SeedVehicle[] = [
  {
    brand: "Toyota",
    model: "Corolla",
    version: "XEi 2.0",
    bodyType: "SEDAN",
    manufactureYear: 2023,
    modelYear: 2023,
    mileageKm: 42000,
    price: 129900,
    transmission: "AUTOMATIC",
    fuel: "FLEX",
    color: "Prata",
    plateEnding: "4",
    doors: 4,
    engine: "2.0 16V",
    powerHp: 177,
    trunkLiters: 470,
    fuelConsumption: "12,8 km/l (cidade)",
    features: ["Central multimídia", "Câmera de ré", "Piloto automático adaptativo", "Bancos de couro", "Sensor de estacionamento", "Ar-condicionado digital"],
    description: "Corolla XEi com revisões em dia, único dono, todo o histórico de manutenção disponível. Ótimo custo-benefício para quem busca conforto e economia.",
    status: "AVAILABLE",
    enteredStockAt: daysAgo(12),
    soldAt: null,
  },
  {
    brand: "Jeep",
    model: "Compass",
    version: "Longitude",
    bodyType: "SUV",
    manufactureYear: 2022,
    modelYear: 2023,
    mileageKm: 38500,
    price: 139900,
    transmission: "AUTOMATIC",
    fuel: "FLEX",
    color: "Preto",
    plateEnding: "7",
    doors: 4,
    engine: "1.3 Turbo",
    powerHp: 185,
    trunkLiters: 438,
    fuelConsumption: "11,4 km/l (cidade)",
    features: ["Teto solar", "Central 10.1\"", "Carregador wireless", "Bancos elétricos", "Assistente de permanência em faixa"],
    description: "Compass Longitude completo, pneus novos, impecável. Ideal para quem quer um SUV robusto sem abrir mão de tecnologia.",
    status: "AVAILABLE",
    enteredStockAt: daysAgo(5),
    soldAt: null,
  },
  {
    brand: "Hyundai",
    model: "Creta",
    version: "Limited",
    bodyType: "SUV",
    manufactureYear: 2023,
    modelYear: 2024,
    mileageKm: 18000,
    price: 134900,
    transmission: "AUTOMATIC",
    fuel: "FLEX",
    color: "Branco",
    plateEnding: "1",
    doors: 4,
    engine: "1.0 Turbo",
    powerHp: 120,
    trunkLiters: 451,
    fuelConsumption: "13,1 km/l (cidade)",
    features: ["Painel digital", "Central multimídia sem fio", "Bancos em couro", "Controle de descida", "Faróis full LED"],
    description: "Creta Limited com baixíssima quilometragem, praticamente zero. Excelente espaço interno e consumo compatível com uso urbano e viagens.",
    status: "AVAILABLE",
    enteredStockAt: daysAgo(2),
    soldAt: null,
  },
  {
    brand: "Volkswagen",
    model: "T-Cross",
    version: "Highline",
    bodyType: "SUV",
    manufactureYear: 2022,
    modelYear: 2022,
    mileageKm: 51200,
    price: 108900,
    transmission: "AUTOMATIC",
    fuel: "FLEX",
    color: "Cinza",
    plateEnding: "9",
    doors: 4,
    engine: "1.4 TSI",
    powerHp: 150,
    trunkLiters: 420,
    fuelConsumption: "12,0 km/l (cidade)",
    features: ["VW Play", "Central multimídia", "Rodas de liga leve 17\"", "Sensor de estacionamento dianteiro e traseiro"],
    description: "T-Cross Highline com motor 1.4 TSI, ótimo desempenho e economia. Revisado, pronto para transferência.",
    status: "AVAILABLE",
    enteredStockAt: daysAgo(45),
    soldAt: null,
  },
  {
    brand: "Chevrolet",
    model: "Onix",
    version: "Premier",
    bodyType: "HATCH",
    manufactureYear: 2023,
    modelYear: 2023,
    mileageKm: 22300,
    price: 84900,
    transmission: "AUTOMATIC",
    fuel: "FLEX",
    color: "Vermelho",
    plateEnding: "2",
    doors: 4,
    engine: "1.0 Turbo",
    powerHp: 116,
    trunkLiters: 300,
    fuelConsumption: "14,2 km/l (cidade)",
    features: ["MyLink+ sem fio", "Central multimídia 8\"", "Piloto automático", "Câmera de ré"],
    description: "Onix Premier automático, economia excelente e visual esportivo. Perfeito primeiro carro ou para uso urbano no dia a dia.",
    status: "AVAILABLE",
    enteredStockAt: daysAgo(1),
    soldAt: null,
  },
  {
    brand: "Fiat",
    model: "Toro",
    version: "Volcano",
    bodyType: "PICKUP",
    manufactureYear: 2021,
    modelYear: 2022,
    mileageKm: 61000,
    price: 119900,
    transmission: "AUTOMATIC",
    fuel: "DIESEL",
    color: "Cinza",
    plateEnding: "5",
    doors: 4,
    engine: "2.0 Turbo Diesel 4x4",
    powerHp: 170,
    trunkLiters: null,
    fuelConsumption: "10,8 km/l (estrada)",
    features: ["Tração 4x4", "Central 8.4\"", "Bancos em couro", "Capota marítima", "Rodas 19\""],
    description: "Toro Volcano diesel 4x4, robusta e completa. Ideal para quem precisa de força e versatilidade sem perder o conforto.",
    status: "AVAILABLE",
    enteredStockAt: daysAgo(98),
    soldAt: null,
  },
  {
    brand: "Honda",
    model: "HR-V",
    version: "EXL",
    bodyType: "SUV",
    manufactureYear: 2023,
    modelYear: 2024,
    mileageKm: 15400,
    price: 149900,
    transmission: "CVT",
    fuel: "FLEX",
    color: "Branco",
    plateEnding: "3",
    doors: 4,
    engine: "1.5 Turbo",
    powerHp: 177,
    trunkLiters: 437,
    fuelConsumption: "12,5 km/l (cidade)",
    features: ["Teto solar", "Honda Sensing", "Bancos em couro", "Central multimídia 9\"", "Carregador por indução"],
    description: "HR-V EXL com pacote completo de segurança Honda Sensing. Baixa km, revisões na concessionária.",
    status: "AVAILABLE",
    enteredStockAt: daysAgo(7),
    soldAt: null,
  },
  {
    brand: "Renault",
    model: "Kwid",
    version: "Intense",
    bodyType: "HATCH",
    manufactureYear: 2022,
    modelYear: 2022,
    mileageKm: 34800,
    price: 58900,
    transmission: "MANUAL",
    fuel: "FLEX",
    color: "Laranja",
    plateEnding: "6",
    doors: 4,
    engine: "1.0 12V",
    powerHp: 70,
    trunkLiters: 290,
    fuelConsumption: "15,6 km/l (cidade)",
    features: ["Central multimídia com Android Auto", "Computador de bordo", "Vidros elétricos"],
    description: "Kwid Intense econômico e ágil, excelente opção de entrada com baixo custo de manutenção.",
    status: "AVAILABLE",
    enteredStockAt: daysAgo(20),
    soldAt: null,
  },
  {
    brand: "Nissan",
    model: "Kicks",
    version: "Advance",
    bodyType: "SUV",
    manufactureYear: 2022,
    modelYear: 2023,
    mileageKm: 29000,
    price: 112900,
    transmission: "CVT",
    fuel: "FLEX",
    color: "Azul",
    plateEnding: "8",
    doors: 4,
    engine: "1.6 16V",
    powerHp: 114,
    trunkLiters: 400,
    fuelConsumption: "13,4 km/l (cidade)",
    features: ["Câmera 360°", "Central multimídia 8\"", "Piloto automático adaptativo", "Chave presencial"],
    description: "Kicks Advance com câmera 360° e ótimo espaço interno, ideal para famílias.",
    status: "RESERVED",
    enteredStockAt: daysAgo(15),
    soldAt: null,
  },
  {
    brand: "Volkswagen",
    model: "Polo",
    version: "GTS",
    bodyType: "HATCH",
    manufactureYear: 2023,
    modelYear: 2023,
    mileageKm: 8900,
    price: 118900,
    transmission: "AUTOMATIC",
    fuel: "FLEX",
    color: "Cinza",
    plateEnding: "0",
    doors: 4,
    engine: "1.4 TSI",
    powerHp: 150,
    trunkLiters: 300,
    fuelConsumption: "12,2 km/l (cidade)",
    features: ["Modo Sport", "Rodas 17\" diamantadas", "Central multimídia digital", "Bancos esportivos"],
    description: "Polo GTS com baixíssima km, praticamente zero, garantia de fábrica vigente.",
    status: "AVAILABLE",
    enteredStockAt: daysAgo(3),
    soldAt: null,
  },
  {
    brand: "Toyota",
    model: "Hilux",
    version: "SRX 4x4",
    bodyType: "PICKUP",
    manufactureYear: 2021,
    modelYear: 2022,
    mileageKm: 72000,
    price: 219900,
    transmission: "AUTOMATIC",
    fuel: "DIESEL",
    color: "Branco",
    plateEnding: "1",
    doors: 4,
    engine: "2.8 Turbo Diesel 4x4",
    powerHp: 204,
    trunkLiters: null,
    fuelConsumption: "9,8 km/l (estrada)",
    features: ["Tração 4x4", "Central multimídia", "Bancos em couro", "Controle de descida", "Diferencial bloqueável"],
    description: "Hilux SRX 4x4 diesel, revisada, pneus novos, pronta para trabalho pesado ou aventura.",
    status: "AVAILABLE",
    enteredStockAt: daysAgo(60),
    soldAt: null,
  },
  {
    brand: "Jeep",
    model: "Renegade",
    version: "Sport",
    bodyType: "SUV",
    manufactureYear: 2022,
    modelYear: 2022,
    mileageKm: 47000,
    price: 94900,
    transmission: "AUTOMATIC",
    fuel: "FLEX",
    color: "Cinza",
    plateEnding: "4",
    doors: 4,
    engine: "1.3 Turbo",
    powerHp: 185,
    trunkLiters: 320,
    fuelConsumption: "11,9 km/l (cidade)",
    features: ["Central multimídia 8.4\"", "Sensor de estacionamento", "Câmera de ré", "Piloto automático"],
    description: "Renegade Sport com bom custo-benefício, ideal para cidade e estrada.",
    status: "AVAILABLE",
    enteredStockAt: daysAgo(33),
    soldAt: null,
  },
  {
    brand: "Fiat",
    model: "Pulse",
    version: "Drive",
    bodyType: "SUV",
    manufactureYear: 2023,
    modelYear: 2023,
    mileageKm: 26500,
    price: 89900,
    transmission: "MANUAL",
    fuel: "FLEX",
    color: "Vermelho",
    plateEnding: "7",
    doors: 4,
    engine: "1.3 16V",
    powerHp: 107,
    trunkLiters: 370,
    fuelConsumption: "13,0 km/l (cidade)",
    features: ["Central multimídia 10.1\"", "Ar-condicionado digital", "Comandos no volante"],
    description: "Pulse Drive completo, econômico, ótima opção custo-benefício em SUV compacto.",
    status: "AVAILABLE",
    enteredStockAt: daysAgo(9),
    soldAt: null,
  },
  {
    brand: "Honda",
    model: "Civic",
    version: "Touring",
    bodyType: "SEDAN",
    manufactureYear: 2023,
    modelYear: 2024,
    mileageKm: 12000,
    price: 189900,
    transmission: "CVT",
    fuel: "GASOLINE",
    color: "Preto",
    plateEnding: "2",
    doors: 4,
    engine: "1.5 Turbo",
    powerHp: 174,
    trunkLiters: 519,
    fuelConsumption: "13,8 km/l (cidade)",
    features: ["Teto solar", "Bancos em couro ventilados", "Honda Sensing", "Head-up display", "Som premium Bose"],
    description: "Civic Touring topo de linha, praticamente novo, completíssimo.",
    status: "AVAILABLE",
    enteredStockAt: daysAgo(4),
    soldAt: null,
  },
  {
    brand: "Chevrolet",
    model: "Tracker",
    version: "Premier",
    bodyType: "SUV",
    manufactureYear: 2022,
    modelYear: 2023,
    mileageKm: 31000,
    price: 116900,
    transmission: "AUTOMATIC",
    fuel: "FLEX",
    color: "Branco",
    plateEnding: "9",
    doors: 4,
    engine: "1.2 Turbo",
    powerHp: 133,
    trunkLiters: 410,
    fuelConsumption: "13,6 km/l (cidade)",
    features: ["Central multimídia 10.1\"", "Piloto automático adaptativo", "Chave presencial", "Bancos em couro"],
    description: "Tracker Premier completa, único dono, revisões na concessionária.",
    status: "SOLD",
    enteredStockAt: daysAgo(70),
    soldAt: daysAgo(2),
  },
];

// A concessionária real costuma ter mais de uma unidade do mesmo
// modelo/versão em estoque. Em vez de escrever ~50 anúncios à mão, geramos
// variantes adicionais de cada modelo já cadastrado acima (mesma
// família/versão, variando cor/ano/km/preço/final de placa/tempo em
// estoque) até chegar perto de 50 veículos — mantendo o mesmo padrão de
// dado 100% fictício e o sistema de fotos-placeholder existente.
const EXTRA_COLORS = ["Prata", "Preto", "Branco", "Cinza", "Vermelho", "Azul", "Marrom"];

function buildVariants(rng: Rng, target: number): SeedVehicle[] {
  const variants: SeedVehicle[] = [];
  let i = 0;
  while (variants.length < target) {
    const source = base[i % base.length];
    i += 1;
    const yearJitter = randInt(rng, -1, 1);
    const modelYear = source.modelYear + yearJitter;
    const manufactureYear = Math.min(source.manufactureYear + yearJitter, modelYear);
    const priceJitter = randInt(rng, -6, 6) / 100; // ±6%
    const price = Math.round((source.price * (1 + priceJitter)) / 100) * 100;
    const mileageKm = Math.max(0, source.mileageKm + randInt(rng, -12000, 18000));
    const status: Vehicle["status"] = chance(rng, 0.08)
      ? "RESERVED"
      : chance(rng, 0.06)
        ? "PREPARING"
        : "AVAILABLE";
    const enteredStockAt = daysAgo(randInt(rng, 0, 140));
    variants.push({
      ...source,
      color: pick(rng, EXTRA_COLORS),
      plateEnding: String(randInt(rng, 0, 9)),
      modelYear,
      manufactureYear,
      price,
      mileageKm,
      status,
      enteredStockAt,
      soldAt: null,
    });
  }
  return variants;
}

const allVehicles: SeedVehicle[] = [...base, ...buildVariants(mulberry32(20260817), 35)];

const usedSlugs = new Set<string>();
function uniqueSeedSlug(v: SeedVehicle): string {
  const root = vehicleSlug(v);
  let candidate = root;
  let n = 2;
  while (usedSlugs.has(candidate)) {
    candidate = `${root}-${n}`;
    n += 1;
  }
  usedSlugs.add(candidate);
  return candidate;
}

export const seedVehicles: Vehicle[] = allVehicles.map((v, index) => {
  const id = `veh_${(index + 1).toString().padStart(3, "0")}`;
  const angles = ["Frente", "Traseira", "Lateral", "Interior"];
  return {
    ...v,
    id,
    slug: uniqueSeedSlug(v),
    source: "SITE",
    createdAt: v.enteredStockAt,
    updatedAt: v.enteredStockAt,
    photos: angles.map((angle, i) => ({
      id: `${id}_photo_${i}`,
      url: "",
      position: i,
      isCover: i === 0,
    })),
  };
});
